/**
 * Class which represents each library item
 *
 * @property {String} v_id Autogenerated id to use in Vue components
 */
class Media {
    constructor(id, collectionName, fileName, mimeType, file, url, thumbnail) {
        this.v_id = Math.random().toString(36).substring(3);
        this.id = id;
        this.collection_name = collectionName;
        this.file_name = fileName;
        this.mime_type = mimeType;
        this.file = file;
        this.url = url;
        this.thumbnail = thumbnail;
    }

    /**
     *
     * @returns {Media}
     */
    static fromObject(obj){
        return new Media(obj.id, obj.collection_name, obj.file_name, obj.mime_type, null, obj.url, obj.thumbnail)
    }
}

export default Media